export const site = {
  name: "Esencia Hair Studio",
  shortName: "Esencia",
  tagline: "Beautiful hair. Effortlessly you.",
  url: "https://esenciahair.co.nz",
  email: "Rachsu99@gmail.com",
  instagram: "https://www.instagram.com/hairbyrachel.nz?igsh=MXNiemsxM3E0N3VucA%3D%3D&utm_source=qr",
  instagramHandle: "@hairbyrachel.nz",
};

export const pricingNote =
  "Keratin and Nanoplasty prices are based on hair length, thickness and the amount of product required. Final pricing will be confirmed following consultation.";

export const services = [
  {
    slug: "haircuts",
    visible: true,
    file: "haircuts.html",
    name: "Ladies Haircuts",
    eyebrow: "Shape · movement · ease",
    summary: "A considered cut shaped around your hair, personal style and everyday routine.",
    intro: "A thoughtful haircut begins with listening. We consider the way your hair naturally falls, how you like to wear it and how much styling you want to do at home.",
    suit: "Ideal when you want to refresh your shape, restore movement or create a more manageable everyday style.",
    startingPrice: "$85",
    image: "assets/images/studio/brunette-waves.webp",
    width: 1080,
    height: 1322,
    alt: "Soft brunette waves styled at Esencia Hair Studio",
    benefits: ["Personal consultation", "Shape tailored to you", "Wearable finish", "Styling guidance"],
    prices: [
      ["Ladies Haircut", "$85"],
      ["Shampoo, Treatment & Haircut", "$95"],
    ],
    priceDescriptions: [
      "Includes shampoo, haircut & blow wave.",
      "Includes shampoo, treatment with a 5-minute relaxing scalp massage, haircut & blow wave.",
    ],
  },
  {
    slug: "keratin",
    visible: true,
    file: "keratin.html",
    name: "Keratin Smoothing",
    eyebrow: "Smooth · soft · manageable",
    summary: "Keratin smoothing designed to reduce frizz, soften texture and make everyday styling easier.",
    intro: "Tired of frizzy, unruly hair? Our Keratin Smoothing Treatment is designed to reduce frizz, soften texture, and make everyday styling easier. This professional salon treatment smooths the hair while keeping it soft, natural, and manageable — without making it look flat or overly straight.",
    suit: "Perfect for clients who want less frizz, smoother hair, and a polished finish that still feels like them.",
    startingPrice: "from $180",
    image: "assets/images/studio/glossy-brunette.webp",
    width: 1080,
    height: 1319,
    alt: "Glossy brunette hair after a smoothing service",
    benefits: [
      "Reduces frizz and flyaways",
      "Makes hair smoother and easier to manage",
      "Helps reduce styling time",
      "Adds softness, shine, and a polished finish",
      "Makes blow-drying and straightening easier",
      "Hair still feels natural and flexible — not stiff or flat",
      "Results can last up to 3 months with the right aftercare",
    ],
    prices: [
      ["Short Hair", "from $180"],
      ["Medium Hair", "from $230"],
      ["Long Hair", "from $280"],
      ["Extra Long / Thick Hair", "from $330"],
    ],
  },
  {
    slug: "nanoplasty",
    visible: true,
    file: "nanoplasty.html",
    name: "Nanoplasty",
    eyebrow: "Sleek · glossy · refined",
    summary: "An advanced smoothing service for a sleek, glossy and more manageable finish.",
    intro: "Nanoplasty is an advanced smoothing option for clients wanting a sleeker finish and more manageable hair. A consultation is essential so we can assess your hair and desired result.",
    suit: "It may suit clients looking for a sleeker overall finish and a significant change in daily manageability, subject to an individual hair assessment.",
    startingPrice: "from $280",
    image: "assets/images/studio/dark-curls.webp",
    width: 1080,
    height: 1338,
    alt: "Defined dark curls with a glossy finish",
    benefits: ["Intense smoothing", "Frizz reduction", "Sleek finish", "Glossy appearance", "Softer feel", "Easier daily styling"],
    prices: [
      ["Short Hair", "from $280"],
      ["Medium Hair", "from $340"],
      ["Long Hair", "from $400"],
      ["Extra Long / Thick Hair", "from $550"],
    ],
  },
  {
    slug: "hair-extensions",
    visible: true,
    file: "hair-extensions.html",
    name: "Hair Extensions",
    eyebrow: "Length · volume · seamless",
    summary: "Personalised Tape and K-Tip extensions chosen to blend beautifully with your natural hair.",
    intro: "Hair extensions are a personalised service. Rachel will assess your natural hair, desired result and the best extension method for a seamless, comfortable finish.",
    suit: "A consultation is essential to match colour, length, density and the most suitable application method.",
    startingPrice: "Price on Consultation",
    image: "assets/images/studio/tape-extensions.webp",
    width: 900,
    height: 1944,
    alt: "Long blonde tape-in extensions with a seamless finish",
    benefits: ["Tailored colour match", "Natural-looking placement", "Method chosen for your hair", "Consultation-led plan"],
    prices: [
      ["Tape Extensions", "Price on Consultation"],
      ["K-Tip Extensions", "Price on Consultation"],
    ],
    priceDescriptions: [
      "The most common and gentle method. Lightweight, flat, and comfortable — ideal for adding volume and length with a seamless blend.",
      "A strand-by-strand method for a very natural finish. Ideal for customised volume, movement, and long-lasting results.",
    ],
  },
  {
    slug: "extension-removal",
    visible: true,
    file: "extension-removal.html",
    name: "Extension Removal",
    eyebrow: "Professional removal with care",
    summary: "Careful, professional removal to protect the condition of your natural hair.",
    intro: "Extensions should always be removed professionally to keep your natural hair comfortable, healthy and ready for its next style.",
    suit: "Ideal when you are ready for a refresh, reapplication or a break from extensions.",
    startingPrice: "from $60",
    image: "assets/images/studio/k-tip-application.webp",
    width: 900,
    height: 1944,
    alt: "Rachel carefully applying a K-Tip extension",
    benefits: ["Careful technique", "Natural hair considered", "Ready for your next appointment"],
    prices: [
      ["Tape Removal", "from $60"],
      ["K-Tip Removal", "from $100"],
    ],
    priceDescriptions: [
      "Safe, professional removal to protect your natural hair and avoid unnecessary damage.",
      "Carefully removed strand-by-strand to keep your hair healthy and comfortable.",
    ],
    extraNote: "Removal pricing may vary depending on the amount of extensions and time required.",
  },
  {
    slug: "styling",
    visible: true,
    file: "styling.html",
    name: "Styling",
    eyebrow: "Polished · effortless · beautiful",
    summary: "A polished finish for an occasion, a confidence boost or simply a beautiful hair day.",
    intro: "Whether you would like smooth movement, soft waves or a more occasion-ready finish, styling is tailored to your hair and the look you want to wear.",
    suit: "Perfect for an event, a night out or whenever you want your hair to feel especially put together.",
    startingPrice: "from $45",
    image: "assets/images/studio/half-up-style.webp",
    width: 1080,
    height: 1342,
    alt: "Soft half-up hairstyle with a floral clip",
    benefits: ["Personalised finish", "Soft movement or polished shape", "Occasion-ready styling"],
    prices: [
      ["Shampoo & Blow Wave", "$55"],
      ["Curls / Styling", "$45"],
    ],
    priceDescriptions: [
      "Includes shampoo, relaxing scalp massage, and blow wave for a smooth, polished finish.",
      "Soft waves, bouncy curls, or a styled look for any occasion.",
    ],
    extraNote: "Extra Long / Thick Hair — +$10",
  },
];

export const treatmentFaqs = [
  ["How much does Keratin smoothing cost?", "Pricing starts from $180 and varies with hair length, thickness and the amount of product required. Final pricing is confirmed following consultation."],
  ["How long do Keratin results last?", "Results can last up to 3 months with the right aftercare."],
  ["How do I know which smoothing treatment is right for me?", "Start with a consultation. Rachel can assess your hair, listen to your desired finish and guide you toward the most suitable service."],
  ["How long will my appointment take?", "Most appointments take approximately 1–2 hours depending on hair length and thickness."],
  ["Do extensions require a consultation?", "Yes. A consultation is essential so we can match colour, assess your natural hair and recommend the most suitable method."],
];

export const galleryImages = [
  ["assets/images/studio/bridal-braid.webp", 1080, 1331, "Floral braided hairstyle", "Styling"],
  ["assets/images/studio/brunette-waves.webp", 1080, 1322, "Soft brunette waves", "Haircuts"],
  ["assets/images/studio/glossy-brunette.webp", 1080, 1319, "Long glossy brunette curls", "Keratin Smoothing"],
  ["assets/images/studio/dark-curls.webp", 1080, 1338, "Defined dark curls", "Nanoplasty"],
  ["assets/images/studio/half-up-style.webp", 1080, 1342, "Half-up styling with a floral clip", "Styling"],
  ["assets/images/studio/blonde-dimension.webp", 1080, 1340, "Dimensional blonde waves", "Colour & Styling"],
  ["assets/images/studio/soft-blonde-waves.webp", 900, 1944, "Soft blonde waves", "Extensions"],
  ["assets/images/studio/highlighted-waves.webp", 1080, 1343, "Highlighted brunette waves", "Extensions"],
  ["assets/images/studio/tape-extensions-styled.webp", 900, 1944, "Styled tape-in extensions", "Tape Extensions"],
  ["assets/images/studio/k-tip-extensions.webp", 900, 1944, "K-Tip extension result", "K-Tip Extensions"],
];
