export const site = {
  name: "Esencia Hair Studio",
  shortName: "Esencia",
  tagline: "Beautiful hair. Effortlessly you.",
  url: "https://esenciahair.co.nz",
  email: "Hello@esenciahair.co.nz",
  bookingsEmail: "Bookings@esenciahair.co.nz",
  instagram: "https://www.instagram.com/hairbyrachel.nz?igsh=MXNiemsxM3E0N3VucA%3D%3D&utm_source=qr",
  instagramHandle: "@hairbyrachel.nz",
};

export const pricingNote =
  "Keratin prices are based on hair length, thickness and the amount of product required. Final pricing will be confirmed following consultation.";

export const services = [
  {
    slug: "haircuts",
    visible: true,
    file: "haircuts.html",
    name: "Ladies Haircuts",
    eyebrow: "Shape · movement · ease",
    summary: "A considered cut shaped around your hair, personal style and everyday routine.",
    intro: "A thoughtful haircut begins with listening. We consider the way your hair naturally falls, how you like to wear it and how much styling you want to do at home.",
    suit: "Ideal when you want to refresh your shape, restore movement or create a more manageable everyday style.",
    startingPrice: "$85",
    image: "assets/images/studio/brunette-waves.webp",
    width: 1080,
    height: 1322,
    alt: "Soft brunette waves styled at Esencia Hair Studio",
    benefits: ["Personal consultation", "Shape tailored to you", "Wearable finish", "Styling guidance"],
    prices: [
      ["Ladies Haircut", "$85"],
      ["Shampoo, Treatment & Haircut", "$95"],
    ],
    priceDescriptions: [
      "Includes shampoo, haircut & blow wave.",
      "Includes shampoo, treatment with a 5-minute relaxing scalp massage, haircut & blow wave.",
    ],
  },
  {
    slug: "keratin",
    visible: true,
    file: "keratin.html",
    name: "Keratin Smoothing",
    eyebrow: "Smooth · soft · manageable",
    summary: "Professional StraightOut formaldehyde-free Keratin smoothing for softer, shinier and more manageable hair.",
    intro: "Tired of frizzy, unruly hair? Our professional StraightOut Formaldehyde-Free Keratin Treatment is designed to reduce frizz and unwanted volume, soften texture, and make everyday styling easier. It smooths the hair while keeping it soft, natural, and manageable — without making it look flat or overly straight.",
    suit: "Perfect for clients who want less frizz, smoother hair, and a polished finish that still feels like them.",
    startingPrice: "from $180",
    image: "assets/images/studio/glossy-brunette.webp",
    width: 1080,
    height: 1320,
    alt: "Glossy brunette hair after a smoothing service",
    benefits: [
      "Reduces frizz and unwanted volume",
      "Makes hair smoother and easier to manage",
      "Helps reduce styling time",
      "Adds softness, shine, and a polished finish",
      "Makes blow-drying and straightening easier",
      "Formaldehyde-free professional formula",
      "Hair still feels natural and flexible — not stiff or flat",
      "Results can last up to 3 months with the right aftercare",
      "Complimentary take-home shampoo and conditioner",
    ],
    prices: [
      ["Short Hair", "from $180"],
      ["Medium Hair", "from $230"],
      ["Long Hair", "from $280"],
      ["Extra Long / Thick Hair", "from $330"],
    ],
  },
  {
    slug: "nanoplasty",
    visible: true,
    file: "nanoplasty.html",
    name: "Nanoplasty",
    eyebrow: "Sleek · glossy · refined",
    summary: "Advanced hair straightening and restoring treatment for long-lasting smoothness, shine and frizz control.",
    intro: "Nanoplasty is an advanced hair straightening and restoring treatment that smooths, hydrates and reconstructs the hair fibre using innovative nanoparticle technology. It delivers long-lasting straightness, intense shine and frizz control without harsh chemicals.",
    suit: "Curly, frizzy or fluffy hair; damaged or over-processed hair; bleached hair; blonde and grey hair; and fine or thick hair.",
    startingPrice: "from $280",
    image: "assets/images/studio/nanoplasty-floractive.jpeg",
    width: 1556,
    height: 2048,
    alt: "Floractive Nanoplasty treatment products held in the Esencia Hair Studio",
    benefits: ["Ultra-Sleek Long-Lasting Results", "100% Frizz Freedom", "Mirror-Like Shine", "Deep Fibre Restoration", "Clean, Vegan Formula", "Style Your Way"],
    prices: [
      ["Short Hair", "from $280"],
      ["Medium Hair", "from $340"],
      ["Long Hair", "from $400"],
      ["Extra Long / Thick Hair", "from $550"],
    ],
  },
  {
    slug: "hair-extensions",
    visible: true,
    file: "hair-extensions.html",
    name: "Hair Extensions",
    eyebrow: "Length · volume · seamless",
    summary: "Personalised Tape and K-Tip extensions chosen to blend beautifully with your natural hair.",
    intro: "Hair extensions are a personalised service. Rachel will assess your natural hair, desired result and the best extension method for a seamless, comfortable finish.",
    suit: "A consultation is essential to match colour, length, density and the most suitable application method.",
    startingPrice: "Price on Consultation",
    image: "assets/images/studio/tape-in-extensions-1.webp",
    width: 1080,
    height: 1878,
    alt: "Long blonde tape-in extensions styled in soft waves",
    benefits: ["Tailored colour match", "Natural-looking placement", "Method chosen for your hair", "Consultation-led plan"],
    prices: [
      ["Tape Extensions", "Price on Consultation"],
      ["K-Tip Extensions", "Price on Consultation"],
    ],
    priceDescriptions: [
      "The most common and gentle method. Lightweight, flat, and comfortable — ideal for adding volume and length with a seamless blend.",
      "A strand-by-strand method for a very natural finish. Ideal for customised volume, movement, and long-lasting results.",
    ],
  },
  {
    slug: "extension-removal",
    visible: true,
    file: "extension-removal.html",
    name: "Extension Removal",
    eyebrow: "Professional removal with care",
    summary: "Careful, professional removal to protect the condition of your natural hair.",
    intro: "Extensions should always be removed professionally to keep your natural hair comfortable, healthy and ready for its next style.",
    suit: "Ideal when you are ready for a refresh, reapplication or a break from extensions.",
    startingPrice: "from $60",
    image: "assets/images/studio/k-tip-application.webp",
    width: 947,
    height: 1668,
    alt: "Rachel carefully applying a K-Tip extension",
    benefits: ["Careful technique", "Natural hair considered", "Ready for your next appointment"],
    prices: [
      ["Tape Extension Removal", "from $60"],
      ["K-Tip Extension Removal", "from $100"],
    ],
    priceDescriptions: [
      "Safe, professional removal to protect your natural hair and avoid unnecessary damage.",
      "Carefully removed strand-by-strand to keep your hair healthy and comfortable.",
    ],
    extraNote: "Removal pricing may vary depending on the amount of extensions and time required.",
  },
  {
    slug: "styling",
    visible: true,
    file: "styling.html",
    name: "Styling",
    eyebrow: "Polished · effortless · beautiful",
    summary: "A polished finish for an occasion, a confidence boost or simply a beautiful hair day.",
    intro: "Whether you would like smooth movement, soft waves or a more occasion-ready finish, styling is tailored to your hair and the look you want to wear.",
    suit: "Perfect for an event, a night out or whenever you want your hair to feel especially put together.",
    startingPrice: "from $45",
    image: "assets/images/studio/half-up-style.webp",
    width: 1080,
    height: 1340,
    alt: "Soft half-up hairstyle with a floral clip",
    benefits: ["Personalised finish", "Soft movement or polished shape", "Occasion-ready styling"],
    prices: [
      ["Shampoo & Blow-Dry", "$55"],
      ["Dry Style – Curls & Waves", "$45"],
    ],
    priceDescriptions: [
      "Includes shampoo, relaxing scalp massage, and a blow-dry for a smooth, polished finish.",
      "Soft waves, bouncy curls, or a styled look for any occasion.",
    ],
    extraNote: "Extra Long / Thick Hair — +$10",
  },
];

export const treatmentFaqs = [
  ["How much does Keratin smoothing cost?", 'Pricing starts <span data-price-key="keratin-short">from $180</span> and varies with hair length, thickness and the amount of product required. Final pricing is confirmed following consultation.', true],
  ["How long do Keratin results last?", "Results can last up to 3 months with the right aftercare."],
  ["How do I know which smoothing treatment is right for me?", "Start with a consultation. Rachel can assess your hair, listen to your desired finish and guide you toward the most suitable service."],
  ["How long will my appointment take?", "Most appointments take approximately 1–2 hours depending on hair length and thickness."],
  ["Do extensions require a consultation?", "Yes. A consultation is essential so we can match colour, assess your natural hair and recommend the most suitable method."],
];

export const nanoplastyFaqs = [
  ["How long does Nanoplasty last?", "Results typically last between 6 and 8 months, depending on your natural hair type, aftercare routine and lifestyle. Your regrowth will grow through naturally while your mid-lengths and ends remain smooth."],
  ["Is Nanoplasty safe?", "Yes. Nanoplasty is formaldehyde-free, vegan-friendly and cruelty-free. The process does not produce harsh fumes, making it a comfortable experience for both you and your stylist. It is suitable for coloured and chemically treated hair. However, it is not recommended during pregnancy due to hormonal changes that may affect results."],
  ["Can I colour my hair after Nanoplasty?", "Yes, tinting, toning and deposit colour services can be performed immediately after the Nanoplasty process is completed. If bleaching is required, we recommend waiting two weeks before or after your Nanoplasty treatment to protect the integrity of your hair. Your stylist will guide you based on your specific service."],
  ["Can I style my hair straight away?", "Yes. After your treatment, your hair is ready to wear straight, waved or curled immediately. Nanoplasty improves manageability, so styling becomes quicker and easier."],
  ["How long does the appointment take?", "A full Nanoplasty service usually takes approximately 3.5 to 4 hours. The exact timing depends on your hair length, thickness and desired result."],
  ["Should I wash my hair before my appointment?", "Yes. Please arrive with freshly shampooed and conditioned hair that is completely product-free. Avoid oils, leave-in products, dry shampoo or styling products before your appointment to ensure optimal results."],
  ["Aftercare & Maintenance", `<p>To help your Nanoplasty results last as long as possible, we recommend following these simple aftercare tips:</p><ul><li>Use professional salon-quality shampoo and conditioner containing a safe amount of good-quality sulphates. We do not recommend sulphate-free shampoo. Your stylist can recommend the most suitable products for your hair type, and Floractive haircare is also available online.</li><li>You can wash, tie up, curl or style your hair the same day if you wish — there is no waiting period after treatment.</li><li>Blast-dry your hair after washing, particularly if your hair is blonde, fragile or chemically treated.</li><li>Do not go to bed with wet hair. Always blast-dry before sleeping to maintain the integrity of the hair fibre.</li><li>Before entering chlorinated or salt water, apply a leave-in treatment or protective product where possible, then rinse your hair afterwards.</li><li>Always use a heat protectant with hot styling tools.</li><li>Use a good-quality hair oil, such as Floractive Moringa Oil or Wella Ultimate Smooth, to keep hair hydrated and protected.</li><li>With the correct homecare, results can last up to 8 months, although longevity varies with hair type, lifestyle and maintenance.</li></ul>`, true],
  ["Should I use a sulphate-free shampoo?", "Not necessarily. A common misconception is that sulphate-free shampoos are always the best choice after every smoothing treatment, but that is not the case with Nanoplasty. For the best results, we recommend a professional salon-quality shampoo and conditioner designed to cleanse thoroughly without being overly harsh. As Nanoplasty leaves hair smooth and deeply conditioned, styling products, oils and environmental residue can build up over time. If it is not removed effectively, hair can feel heavier, duller and less smooth. It will not remove the Nanoplasty treatment itself, but the right professional homecare helps maintain the glossy finish for as long as possible."],
];

export const galleryImages = [
  ["assets/images/studio/bridal-braid.webp", 1080, 1332, "Floral braided hairstyle", "Styling"],
  ["assets/images/studio/brunette-waves.webp", 1080, 1322, "Soft brunette waves", "Haircuts"],
  ["assets/images/studio/glossy-brunette.webp", 1080, 1320, "Long glossy brunette curls", "Keratin Smoothing"],
  ["assets/images/studio/nanoplasty-floractive.jpeg", 1556, 2048, "Floractive Nanoplasty treatment products", "Nanoplasty"],
  ["assets/images/studio/half-up-style.webp", 1080, 1340, "Half-up styling with a floral clip", "Styling"],
  ["assets/images/studio/blonde-dimension.webp", 1080, 1338, "Dimensional blonde waves", "Colour & Styling"],
  ["assets/images/studio/soft-blonde-waves.webp", 947, 1674, "Soft blonde waves", "Extensions"],
  ["assets/images/studio/highlighted-waves.webp", 1080, 1344, "Highlighted brunette waves", "Extensions"],
  ["assets/images/studio/tape-extensions-styled.webp", 947, 1685, "Styled tape-in extensions", "Tape Extensions"],
  ["assets/images/studio/k-tip-extensions.webp", 947, 1677, "K-Tip extension result", "K-Tip Extensions"],
];
